### ISSUE TITLE
Erstellung eines Konzepts

### ISSUE THREAD

**Issue by code-later** [code-later/FDDWSS22_BreuerFaske#2]
## Feature

Als Dozent:in möchte ich ein Konzept üner die geplante Anwendung einsehen können. Das Konzept soll dabei den Problemraum beschreiben und abgrenzen. Darüber hinaus möchte ich erste _Events_, _Domänen_ sowie _Kommunikationsflüsse_ identifiziert sehen. Das Konzept möchte ich hier im Repository in einsehen können.

## Tasks

- [x] Erstellen eines Konzepts
- [x] Auflistung wesentlicher Events
- [x] Auflistung wesentlicher Domänen
- [x] Auflistung wesentlicher Kommunikationsflüsse
- [x] Erstellung einer `README.md` mit einer Referenz auf das Konzept
