### ISSUE TITLE
Docker Umgebung aufsetzen

### ISSUE THREAD

**Issue by code-later** [code-later/FDDWSS22_BreuerFaske#4]
## Feature

Als Entwickler:in möchte ich die Anwendung lokal mit Docker und `docker compose` betreiben. Für den Anfang reicht eine statische Seite mit "Willkommen". Die weiteren Dienste und Abhängigkeiten werden im weiteren Verlauf erstellt.

## Tasks

- [x] `Dockerfile` für die Einstiegsseite
- [x] `docker-compose.yml` mit zwei Diensten
- [x] Ein NodeJS Beispiel zeigen
- [x] Einfache Datenbank-Verbindung demonstrieren
- [x] Reverse Proxy zur Umgehung von CORS-Problemen einrichten
