### ISSUE TITLE
Game Service hinzufügen

### ISSUE THREAD

**Issue by code-later** [code-later/FDDWSS22_BreuerFaske#6]
## Feature / Bug

Als Nutzer:in möchte ich mich nach der Anmeldung ein neues Spiel starten können.

## Tasks

- [ ] `game_service` aufsetzen
- [ ] Authentifizierung an den `game_service` via JWT weiterreichen
- [ ] `auth_service` soll Events nach Registrierung veröffentlichen
- [ ] "Willkommen"-E-Mail nach Registrierung über `notification_service` verschicken
